spring:
  application:
    name: adminportal
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: <<>>>>
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            scope: openid,profile,email,User.Read,api://0eb346b3-9347-41f0-8fd6-137cc2d030e7/limitsapi.read
            client-name: Microsoft Entra ID
            issuer-uri: https://login.microsoftonline.com/<<>>>>/v2.0
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/<<>>>>/v2.0

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: DEBUG
server:
  ssl:
    key-alias: adminportal-sslcert
    key-store-type: AzureKeyVault
    trust-store-type: AzureKeyVault
  port: 8443
azure:
  keyvault:
    uri: https://ganeshrnair-app-vault1.vault.azure.net/
limitsapi:
  url: https://ganeshrnair-adminportal.trafficmanager.net:8444/api/dailylimit