spring:
  application:
    name: adminportal
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: <<>>>>
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            scope: openid, profile, email
            client-name: Microsoft Entra ID
            issuer-uri: https://login.microsoftonline.com/<<>>>>/v2.0
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/<<>>>>/v2.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
