spring:
  application:
    name: limitsapi
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: https://login.microsoftonline.com/8c07552d-ec95-4eab-be2a-e9609b47a162/v2.0

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
server:
  port: 8081
